### ISSUE TITLE
doc_scores not defined when using weighted selection

### ISSUE THREAD

**Issue by cagey-squirrel** [OpenBMB/VisRAG#28]
When running generate.py with following params:
`--model_name MiniCPMV2.0 --dataset_name ChartQA --rank 0 --world_size 1 --use_positive_sample 1 --topk 1 --task_type weighted_selection`
I get the error:
`UnboundLocalError: cannot access local variable 'doc_scores' where it is not associated with a value`

**Comment by tcy6** [comment]
Thank you for pointing out this issue! We sincerely apologize for the inconvenience caused by this bug. The issue has been resolved, and the fix involves adding the following lines of code in `generate.py` at lines 163-164:

```python
if task_type == 'weighted_selection':
    doc_scores = len(docid) * [1 / len(docid)]
```
We appreciate your patience and understanding. Please let us know if you encounter any further issues!
