### ISSUE TITLE
微调后的模型推理问题

### ISSUE THREAD

**Issue by tuncha** [OpenBMB/VisRAG#38]
您好！我想使用自定义数据进行微调VisRAG-Ret 我使用的命令为 CUDA_VISIBLE_DEVICES=7 bash scripts/train_retriever/train.sh 2048 16 1 0.02 1 true false config/deepspeed.json 1e-5 false wmean causal 1 true 2 false /data/code/RAG/VisRAG-Ret  /data/code/RAG/parquet 其中parquet文件夹是我按照训练集格式收集的自定义数据 但是训练完后我发现推理时缺失tokenizer.py、modeling_minicpm.py类似的这种文件 我从VisRAG-Ret文件夹中复制了同名文件到训练权重中，这样可以推理但是推理的结果和原始模型完全一致 我感觉模型并没有更新 请问这是什么原因

**Comment by tcy6** [comment]
@tuncha 您好，如果您想要使用自己训练的权重进行推理的话，只需要把`VisRAG-Ret`仓库中的权重替换为您自己训练得到的即可，请问您的步骤是这样的吗，如果是这样的话，照理来说并不会出现以上问题。

**Comment by dbcSep03** [comment]
请问有没有遇到
```
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
[rank1]: Parameter at index 677 with name lm_q.vpm.blocks.25.mlp.fc2.bias has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
```
这个报错，如何解决？谢谢

**Comment by dbcSep03** [comment]
> 您好！我想使用自定义数据进行微调VisRAG-Ret 我使用的命令为 CUDA_VISIBLE_DEVICES=7 bash scripts/train_retriever/train.sh 2048 16 1 0.02 1 true false config/deepspeed.json 1e-5 false wmean causal 1 true 2 false /data/code/RAG/VisRAG-Ret /data/code/RAG/parquet 其中parquet文件夹是我按照训练集格式收集的自定义数据 但是训练完后我发现推理时缺失tokenizer.py、modeling_minicpm.py类似的这种文件 我从VisRAG-Ret文件夹中复制了同名文件到训练权重中，这样可以推理但是推理的结果和原始模型完全一致 我感觉模型并没有更新 请问这是什么原因


请问您有没有出现以下报错，
RuntimeError: Expected to mark a variable ready only once. This error is caused by one of the following reasons: 1) Use of a module parameter outside the `forward` function. Please make sure model parameters are not shared across multiple concurrent forward-backward passes. or try to use _set_static_graph() as a workaround if this module graph does not change during training loop.2) Reused parameters in multiple reentrant backward passes. For example, if you use multiple `checkpoint` functions to wrap the same part of your model, it would result in the same set of parameters been used by different reentrant backward passes multiple times, and hence marking a variable ready multiple times. DDP does not support such use cases in default. You can try to use _set_static_graph() as a workaround if your module graph does not change over iterations.
[rank1]: Parameter at index 677 with name lm_q.vpm.blocks.25.mlp.fc2.bias has been marked as ready twice. This means that multiple autograd engine  hooks have fired for this particular parameter during this iteration.
想问一下，如何解决？谢谢
